### PR TITLE
feat: Implements JVL command for zeroing position encoder, calls on winch startup

### PR DESCRIPTION
**Pull request by figuernd**

### CODE REVIEW

**Comment by rgov** [comment]
There's a typo in the service definition, "registry".

If this is the correct way to do it, then it seems like a good change.

**Comment by figuernd** [comment]
> There's a typo in the service definition, "registry".
> 
> If this is the correct way to do it, then it seems like a good change.

Good catch, fixed

**Comment by figuernd** [comment]
@rgov can you think of any side effects of using this? i.e. position drift from being reset too many times? (Seems unlikely since position is calibrated by CTD depth). Thinking about adding a config option to disable this command as a backup.

**Comment by rgov** [comment]
I have no experience outside this project. I don't think we need to add an option; either it works and we continue using it or it doesn't and we deploy a hot fix to revert back.

It would give me more confidence to know that this is indeed exactly how MacTalk resets the encoder position. We can do that by using MacTalk with WireShark, for example.

**Comment by figuernd** [comment]
> I have no experience outside this project. I don't think we need to add an option; either it works and we continue using it or it doesn't and we deploy a hot fix to revert back.
> 
> It would give me more confidence to know that this is indeed exactly how MacTalk resets the encoder position. We can do that by using MacTalk with WireShark, for example.

Haven't merged yet because I still hope to do this; haven't had the proper setup yet.

**Comment by figuernd** [comment]
I'm going to take a closer look at MacTalk values in the lab next week - but we've been using this in the field long enough that I'm going to merge for now so that I can finally stop rebasing on top of it for every deployment. Will open a new issue if I find anything wrong with the procedure in lab.

**Pull request merged**
